from Tkinter import *

root = Tk()
root.wm_title("brain**** Explained")
root.geometry('{}x{}'.format(460, 380))
root.resizable(width=FALSE, height=FALSE)

title = Label(root, text="Brain****")
title.pack(padx=100)
a = Label(root, text="This language is comprised of a set of 30000 cells all containing 0:")
b = Label(root, text="[0][0][0][0][0][0][0][0][0][0][0]")
c = Label(root, text="It has eight characters with all the others treated as comments.")
d = Label(root, text="The characters are ,.[]<>-+")
e = Label(root, text="Eplanation of each character:\n")
f = Label(root, text=">: Moves one cell to the right\n")
g = Label(root, text="<: Moves one cell to the left\n")
h = Label(root, text="+: Adds one to the current cell\n")
i = Label(root, text="-: Subtracts one from the current cell\n")
j = Label(root, text=".: Prints the ascii value of the current cell to the screen\n")
k = Label(root, text=",: Takes an input from the user and puts that in the current cell\n")
l = Label(root, text="[: goes to the corresponding \']\' if the cells value is 0\n")
m = Label(root, text="]: Goes back to it's corresponding \']\'")
a.pack()
b.pack()
c.pack()
d.pack()
e.pack(anchor='w')
f.pack(anchor='w')
g.pack(anchor='w')
h.pack(anchor='w')
i.pack(anchor='w')
j.pack(anchor='w')
k.pack(anchor='w')
l.pack(anchor='w')
m.pack(anchor='w')
root.mainloop()